timezone:   Etc/UTC
apt_cache_valid_time: 3600

ansible_user: ubuntu
ansible_ssh_user: ubuntu
host_name_var: "{{ ec2_tag_Name }}"

#Use Python3 for remote hosts, as it is installed in Ubuntu 17.04
ansible_python_interpreter: /usr/bin/python3

#Sets the content of /etc/hosts
linux_hosts_file_entries:
  - ip:    127.0.0.1
    name:  "{{ ec2_tag_private_name }}"
  - ip:    "{{ ec2_private_ip_address }}"
    name:  "{{ ec2_tag_private_name }}"
  - ip:    "{{ ec2_private_ip_address }}"
    name:  "{{ ec2_tag_Name }}"
  - ip:    127.0.0.1
    name:  localhost

#Set hostname
linux_host_name: "{{ ec2_tag_Name }}"

#Add repo packages (uncomment if needed)
#linux_add_packages_repositories:
#- repo:

#Install common packages
linux_add_packages_names:
- name: mc #Midnight Commander
- name: unzip
- name: wget
