---

- name: Download WordPress
  get_url:
    url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
    dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
    checksum: "sha1:{{ wordpress_version_checksum }}"
  become: yes

- name: Extract WordPress and Copy to website
  unarchive:
    src: "/tmp/wordpress-{{ wordpress_version }}.tar.gz"
    dest: "{{item.root_dir}}"
    creates: "{{item.root_dir}}/wp-settings.php"
    owner: "{{wordpress_group}}"
    group: "{{wordpress_group}}"
    copy: no
    extra_opts: [--strip-components=1]  #Remove wordpress directory
  become: yes
  with_items: "{{ wordpress_vhosts_ssl | default([])}}"
  when: wordpress_vhosts_ssl is defined and not (wordpress_vhosts_ssl is none or wordpress_vhosts_ssl | trim == '')

- name: Configure WordPress
  template:
    src=wp-config.php
    dest="{{item.root_dir}}/wp-config.php"
  with_items: "{{ wordpress_vhosts_ssl | default([])}}"
  when: wordpress_vhosts_ssl is defined and not (wordpress_vhosts_ssl is none or wordpress_vhosts_ssl | trim == '')
  notify:
    - Restart nginx
